### ISSUE TITLE
Calendar widget rendering issue

### ISSUE THREAD

**Issue by tristan-minimax** [MoAlyousef/fltk-rs-calendar#4]
There is an issue which causes the calendar widget to be rendered directly on to previously rendered widgets. In the included screenshot, the calendar widget has rendered without its title bar and can not be interacted with. The widget that is actually active is the menu bar that is being covered by the calendar (if I use menubar shortcuts, they work -- implying the menubar is active). 

![image](https://github.com/user-attachments/assets/92c03555-ff40-406a-8746-fb4a6cfaf9c9)

The following code generates the shown calendar widget -- note that the first time the calendar is rendered by clicking `date_button` the widget renders and works as expected. Only if `date_button` is clicked again before any other UI is rendered will it fail.
```    
        let mut date_refresher = refresh.clone();
        date_button.set_callback(move |b|{
            let cal = calendar::Calendar::default();
            let new_date = match cal.get_date() {
                Some(d) => {d},
                None => {app::GlobalState::<NaiveDate>::get().with(move |c|{c.clone()})},
            };
            let date_state = app::GlobalState::<NaiveDate>::get();
            let date = date_state.with(move |c|{
                new_date.clone_into(c);
                c.clone()
            });
            b.set_label(&format!("{}", date.format("%Y-%m-%d")));
            date_refresher.do_callback();
        });
```

**Comment by MoAlyousef** [comment]
Hi
Thank you for the report.
Can you try adding `Group::set_current(None::<&Group>);` to the beginning of the callback function, before spawning the calendar. If that works, I'll apply the fix to fltk-calendar.

**Comment by tristan-minimax** [comment]
The fix worked, the widget is now rendering as a separate window every time the callback is called.

Thanks!

**Comment by tristan-minimax** [comment]
fltk-calendar 0.4.1 released, fixing the issue. Closing issue.

Thanks Mo!
